### PR TITLE
Added main.elf for Pancake

### PR DESCRIPTION
**Pull request by mytechnotalent**
**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by mytechnotalent** [comment]
Added Raspberry Pi Pico stripped elf so @radare @trufae can have Radare2 find the entry point for this architecture.

**Comment by trufae** [comment]
Uhm is this file in the elf directory?

**Comment by mytechnotalent** [comment]
I might have misunderstood i thought you wanted the main.elf file this is in the build dir.

**Comment by trufae** [comment]
Should be commited in this directory https://github.com/radareorg/radare2-testbins/tree/master/elf

**Comment by mytechnotalent** [comment]
Moved.

**Comment by trufae** [comment]
thanks! merged

**Pull request merged**
