### PR TITLE
Glibc heap tests

### PR DESCRIPTION
**Pull request by meowmeowxw**
Tests for https://github.com/radareorg/radare2/pull/17534, but they can also be used to tests different glibc. Every binary has a different loader/linker and can be loaded with a different glibc using `-Rsetenv=LD_PRELOAD=bins/elf/libc-2.${version}.so`.
At the moment the glibc tested are:

2.32 (new), 2.31 (ubuntu 20), 2.27 (ubuntu 18)

### CODE REVIEW

**Comment by XVilka** [comment]
@meowmeowxw why `elf/tcache-2.27` is unused? Maybe it's better to add a testcase then?

**Comment by meowmeowxw** [comment]
@XVilka It is replaced by `glibc-heap-2.27`, which has both tcache and fastbins. So it's more flexible if someone wants to test fastbins too.

**Comment by kazarmy** [comment]
Please fix tests
https://github.com/radareorg/radare2/blob/7e2873983539c6e7fe4f0a6ea0ce2dbe168748d3/test/db/archos/linux-x64/dbg_dmht#L1-L26

**Comment by meowmeowxw** [comment]
@kazarmy There is this PR that uses the new files https://github.com/radareorg/radare2/pull/17534

**Pull request merged**
